import { app, BrowserWindow, desktopCapturer, ipcMain, globalShortcut } from 'electron';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

import * as Types from './Types';
import fs from 'fs';
import path from 'path';
import axios from 'axios';
import LCUConnector from 'lcu-connector';
import https from 'https';
import sendQ from './sendQ';


let _GLOBAL_toggle_display_value = true


// Initialize the LCUConnector

const connector = new LCUConnector();

let LCUDatas: Types.LCUDatas = {
    connected: false,
    address: "",
    port: 0,
    username: "",
    password: "",
    protocol: "",
}


connector.on('connect', (data: Types.LCUDatas) => {
    console.log(data);
    //  {
    //    address: '127.0.0.1'
    //    port: 18633,
    //    username: 'riot',
    //    password: H9y4kOYVkmjWu_5mVIg1qQ,
    //    protocol: 'https'
    //  }
    let url = `${data.protocol}://${data.address}:${data.port}`;
    console.log("url:", url);
    LCUDatas = {
        connected: true,
        address: data.address,
        port: data.port,
        username: data.username,
        password: data.password,
        protocol: data.protocol,
    };
    console.log("LCUDatas:", LCUDatas);

    setTimeout(() => {
        POGCardinalInternals.setCameraPreset("obs")

    }, 5000)

})

connector.start();


async function requestLCUEdpoint(method: Types.HTTPMethod = "GET", endpoint: string): Promise<{status: boolean, datas: any}> {
    try {
        const url = `${LCUDatas.protocol}://${LCUDatas.address}:${LCUDatas.port}${endpoint}`;
        console.log("url:", url);
        // Get the response whatever the returned status code
        const response = await axios.request({
            method: method,
            url: url,
            headers: {
                'Authorization': `Basic ${Buffer.from(`${LCUDatas.username}:${LCUDatas.password}`).toString('base64')}`,
            },
            httpsAgent: new https.Agent({
                rejectUnauthorized: false,
            }),
            validateStatus: () => true,
        });

        return {
            status: true,
            datas: response.data
        };

    } catch (err) {
        console.log(`[LCU_Worker] Error#001 while fetching api Datas:`, err);
        return {
            status: false,
            datas: null
        };
    }
}

async function requestLiveClientAPIEndpoint(method: Types.HTTPMethod = "GET", endpoint: string, body={}): Promise<{status: boolean, datas: any}> {
    try {

        const url = "https://127.0.0.1:2999" + endpoint;
        console.log(`requestLiveClientAPIEndpoint. ${method} ${url} ${JSON.stringify(body)}`);
        // Get the response whatever the returned status code
        const response = await axios.request({
            method: method,
            url: url,
            headers: {
                'Authorization': `Basic ${Buffer.from(`${LCUDatas.username}:${LCUDatas.password}`).toString('base64')}`,
            },
            httpsAgent: new https.Agent({
                rejectUnauthorized: false,
            }),
            validateStatus: () => true,
            data: body
        });

        return {
            status: true,
            datas: response.data
        };

    } catch (err) {
        console.log(`[LCU_Worker] Error#001 while fetching api Datas:`, err);
        return {
            status: false,
            datas: null
        };
    }
}





class class_POGCardinalInternals {

    constructor() {}
    
    async setCameraPreset(name: string) {
        const presets: {[key: string]: any } = {
            "sequence": {
                "interfaceAll":             false,
                "interfaceAnnounce":        false,
                "interfaceChat":            false,
                "interfaceFrames":          false,
                "interfaceKillCallouts":    false,
                "interfaceMinimap":         false,
                "interfaceNeutralTimers":   false,
                "interfaceQuests":          false,
                "interfaceReplay":          false,
                "interfaceScore":           false,
                "interfaceScoreboard":      false,
                "interfaceTarget":          false,
                "interfaceTimeline":        false,
                "outlineHover":             false,
                "outlineSelect":            false,
            },
            "obs": {
                "interfaceAll":                 true,
                "interfaceAnnounce":            true,
                "interfaceChat":            false,
                "interfaceFrames":              true,
                "interfaceKillCallouts":        true,
                "interfaceMinimap":             true,
                "interfaceNeutralTimers":   false,
                "interfaceQuests":              true,
                "interfaceReplay":          false,
                "interfaceScore":           false,
                "interfaceScoreboard":          true,
                "interfaceTarget":              true,
                "interfaceTimeline":        false,
                "outlineHover":             false,
                "outlineSelect":            false,
            },
            "fight": {
                "interfaceAll":                 true,
                "interfaceAnnounce":            true,
                "interfaceChat":            false,
                "interfaceFrames":          false,
                "interfaceKillCallouts":        true,
                "interfaceMinimap":             true,
                "interfaceNeutralTimers":   false,
                "interfaceQuests":              true,
                "interfaceReplay":          false,
                "interfaceScore":           false,
                "interfaceScoreboard":          true,
                "interfaceTarget":              true,
                "interfaceTimeline":        false,
                "outlineHover":             false,
                "outlineSelect":            false,
            }

        }
        const datas = presets[name]
        requestLiveClientAPIEndpoint("POST", "/replay/render", datas)
    }

    async teleportTo(name:string) {
        let currentRender = await requestLiveClientAPIEndpoint("GET", "/replay/render")
        let currentCameraPosition = currentRender.datas.cameraPosition
        let currentCameraRotation = currentRender.datas.cameraRotation


        let getCurrentY = currentRender.datas.cameraPosition.y
        const positions: {[key: string]: any } = {
            "drake": {
                "cameraPosition": {
                    "x": 10009.052734375,
                    "y": getCurrentY,
                    "z": 3117.9228515625 + 1500
                },
                "cameraRotation": currentCameraRotation
            },
            "nashor": {
                "cameraPosition": {
                    "x": 4958.11474609375,
                    "y": getCurrentY,
                    "z": 8940.5830078125 + 1500
                },
                "cameraRotation": currentCameraRotation
            },
            "topLane": {
                "cameraPosition": {
                    "x": 2289.0458984375,
                    "y": getCurrentY,
                    "z": 11028.00390625 + 1500
                },
                "cameraRotation": currentCameraRotation
            },
            "midLane": {
                "cameraPosition": {
                    "x": 7377.328125,
                    "y": getCurrentY,
                    "z": 5850.9248046875 + 1500
                },
                "cameraRotation": currentCameraRotation
            },
            "botLane": {
                "cameraPosition": {
                    "x": 12581.97265625,
                    "y": getCurrentY,
                    "z": 956.5654296875 + 1500
                },
                "cameraRotation": currentCameraRotation
            }
        }
        const datas = positions[name]
        await requestLiveClientAPIEndpoint("POST", "/replay/render", { cameraMode: "fps", cameraPosition: currentCameraPosition, cameraRotation: currentCameraRotation })
        await requestLiveClientAPIEndpoint("POST", "/replay/render", datas)
        await requestLiveClientAPIEndpoint("POST", "/replay/render", { cameraMode: "top" })
    }
}

const POGCardinalInternals = new class_POGCardinalInternals()


const _CONFIG_filePath = path.resolve(app.getPath('userData') + '/config.json')
// If file not exists, create it

console.log("_CONFIG_filePath:", _CONFIG_filePath)

import express from 'express';


type Config = {
    "appAPI_port": number,
    "dataTrackerPortableBaseURL": `http://${string}:${number}` | `https://${string}:${number}`
}

function getConfig(): Config {
    const defaultData: Config = {
        "appAPI_port": 8201,
        "dataTrackerPortableBaseURL": "http://127.0.0.1:4000"
    }
    if (!fs.existsSync(_CONFIG_filePath)) {
        fs.writeFileSync(_CONFIG_filePath, JSON.stringify(defaultData, null, 4), 'utf8');
    }
    const _CONFIG_ = fs.existsSync(_CONFIG_filePath) ? JSON.parse(fs.readFileSync(_CONFIG_filePath, 'utf8')) : {};
    return _CONFIG_;
}

// Start simple API
const api = express()

api.get("/fightMode/enable", async (req, res) => {
    mainWindow.webContents.send('fightMode', 'enable');
})

api.get("/fightMode/disable", async (req, res) => {
    mainWindow.webContents.send('fightMode', 'disable');
})

api.get("/fightMode/toggleInGame", async (req, res) => {
    try {
        setTimeout(() => {
            console.log("Sending key q")
            sendQ()
        }, 3000)
        return res.send({status: 200, message: `Toggling in game`})
    } catch (e) {
        console.error(e)
        return res.send({status: 500, message: `Error while toggling in game`, stack: e.stack})
    }    
})

api.get("/teleport/:name", async (req, res) => {
    try {
        await POGCardinalInternals.teleportTo(req.params.name)
        return res.send({status: 200, message: `Teleporting to ${req.params.name}`})
    } catch (e) {
        console.error(e)
        return res.send({status: 500, message: `Error while teleporting to ${req.params.name}`, stack: e.stack})
    }
})

api.get("/cameraPreset/:name", async (req, res) => {
    try {
        await POGCardinalInternals.setCameraPreset(req.params.name)
        return res.send({status: 200, message: `Camera preset set to ${req.params.name}`})
    } catch (e) {
        console.error(e)
        return res.send({status: 500, message: `Error while setting camera preset to ${req.params.name}`, stack: e.stack})
    }
    
})

api.get("/overlay/show", (req, res) => {
    console.log("overlay/show")
    mainWindow.webContents.send('toggle_display', 'show');
    _GLOBAL_toggle_display_value = true
    return res.send({status: 200, message: `Overlay shown`})
})

api.get("/overlay/hide", (req, res) => {
    console.log("overlay/hide")
    mainWindow.webContents.send('toggle_display', 'hide');
    _GLOBAL_toggle_display_value = false
    return res.send({status: 200, message: `Overlay hidden`})
})


api.all('*', (req: any, res: any) => {
    
    res.send({
        status: 200,
        message: `You are connected to the API of POGMonitorOverlay on computerName: ${req.hostname}`
    })
})


/*

API Documentation:

GET /fightMode/enable   -> Enable the fight mode
GET /fightMode/disable  -> Disable the fight mode
GET /fightMode/toggleIngame -> Toggle the in game
GET /teleport/:name     -> Teleport to a specific location
    name: drake | nashor | topLane | midLane | botLane
GET /cameraPreset/:name -> Set the camera preset
    name: obs | sequence | fight
GET /overlay/show       -> Show the overlay
GET /overlay/hide       -> Hide the overlay


*/


api.listen(getConfig()?.appAPI_port, () => {
  console.log(`API listening on port ${getConfig()?.appAPI_port}`)
})




app.commandLine.appendSwitch('enable-experimental-web-platform-features');
app.commandLine.appendSwitch('enable-gpu'); // Enable GPU acceleration


let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    fullscreen: true,
    resizable: false,
    // height: 400,
    // width: 600,
    transparent: true, // Make the window transparent
    alwaysOnTop: true,
    frame: false, // Remove the window frame
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: true,
      contextIsolation: true,
    },
  });

  function toggleMouseEvent(value: boolean) {
    if (value === false) {
      mainWindow.setIgnoreMouseEvents(true, { forward: true });
    } else {
      mainWindow.setIgnoreMouseEvents(false);
    }
  }

  ipcMain.on('mouse-events-disable', (event) => { toggleMouseEvent(false); })
  ipcMain.on('mouse-events-enable', (event) => {  toggleMouseEvent(true); })
  toggleMouseEvent(false);
  // show input box of electron an load the response as URL


  // and load the index.html of the app.
  //mainWindow.loadURL(`${getConfig().dataTrackerPortableBaseURL}/ingame`);
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY)
  // Reput windows on top
  mainWindow.setAlwaysOnTop(true, 'screen-saver');
  

  // set browser window on the 2nd screen
  //mainWindow.setPosition(-1920, 0)
  

  // Open the DevTools.
};

/*
import { GlobalKeyboardListener } from 'node-global-key-listener';
const v = new GlobalKeyboardListener();
console.log("v:", v)
//Log every key that's pressed.
v.addListener(function (e: any, key: any) {
    console.log(
        `${e.name} ${e.state == "DOWN" ? "DOWN" : "UP  "} [${e.rawKey._nameRaw}]`
    );
    console.log(`Event: ${JSON.stringify(e)}, Key: ${JSON.stringify(key)}`);
}).then(() => {
    console.log("Listener added");
}).catch((e) => {
    console.error("Failed to add listener", e);
})
    */

let booleen = true

app.whenReady().then(() => {
    
    
    globalShortcut.register('CTRL+B', (...args:any[]) => {
      console.log('Electron loves global shortcuts!',...args)

      if(_GLOBAL_toggle_display_value === true) {
        mainWindow?.webContents.send('toggle_display', 'hide');
        _GLOBAL_toggle_display_value = false
      } else {
        mainWindow?.webContents.send('toggle_display', 'show');
        _GLOBAL_toggle_display_value = true
      }

      
      

      // Don't block the keypress
    })
    
    
})


// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);


// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.




ipcMain.handle('getSources', async () => {
  return await desktopCapturer.getSources({ types: ['window', 'screen'] })
})

ipcMain.handle('getOperatingSystem', () => {
  return process.platform
})